'use client';

import { useEffect, useRef } from 'react';
import { Terminal } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { useCommand } from '@/hooks/use-command';
import { CommandOutputSkeleton } from '@/components/ui/loading-skeletons';
import { useSelectionStore } from '@/stores/selection-store';
import { useClipboard, useMultiClipboard } from '@/hooks/use-clipboard';
import { toast } from 'sonner';
import { CommandHeader } from './command-output/command-header';
import { SetupCommands } from './command-output/setup-commands';
import { InstallCommands } from './command-output/install-commands';
import { CommandWarnings } from './command-output/command-warnings';
import { EmptyState } from './command-output/empty-state';

export function CommandOutput() {
  const { selectedApps, selectedDistro, sourcePreference } = useSelectionStore();
  const { generate, loading, error, result } = useCommand();

  // Clipboard hooks
  const { copied: copiedAll, copy: copyAll } = useClipboard();
  const { copied: copiedSetup, copy: copySetup } = useClipboard({
    successMessage: 'Setup commands copied!',
  });
  const { copiedItems: copiedCommands, copy: copyCommand } = useMultiClipboard({
    successMessage: 'Command copied!',
  });

  // Track previous values to prevent unnecessary calls
  const prevSelectionRef = useRef<{
    appIds: string;
    distro: string | null;
    source: string | null;
  }>({
    appIds: '',
    distro: null,
    source: null,
  });

  // Auto-generate when selection actually changes or on mount
  useEffect(() => {
    const appIds = Array.from(selectedApps).sort().join(',');
    const prev = prevSelectionRef.current;

    // Check if selection actually changed or if this is initial mount with selections
    const hasChanged =
      prev.appIds !== appIds ||
      prev.distro !== selectedDistro ||
      prev.source !== sourcePreference;

    // Generate if we have selections and (changed OR we have no result yet)
    if (selectedApps.size > 0 && selectedDistro && (hasChanged || !result)) {
      prevSelectionRef.current = {
        appIds,
        distro: selectedDistro,
        source: sourcePreference,
      };
      generate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedApps, selectedDistro, sourcePreference]);

  const handleCopyAll = async () => {
    if (!result) return;

    const fullCommand = [
      ...(result.setupCommands || []),
      ...result.commands,
    ].join('\n\n');

    await copyAll(fullCommand);
  };

  const handleCopySetup = async () => {
    if (!result?.setupCommands) return;
    await copySetup(result.setupCommands.join('\n\n'));
  };

  const handleCopyCommand = async (index: number) => {
    if (!result) return;
    await copyCommand(result.commands[index], index);
  };

  const handleDownload = () => {
    if (!result) return;

    const fullCommand = [
      '#!/bin/bash',
      '# Generated by Linite - Bulk Linux package installer',
      '# https://linite.sagyamthapa.com.np',
      '',
      ...(result.setupCommands || []),
      '',
      ...result.commands,
    ].join('\n');

    const blob = new Blob([fullCommand], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'linite-install.sh';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Script downloaded!');
  };

  // Empty state
  if (selectedApps.size === 0 || !selectedDistro) {
    return <EmptyState />;
  }

  // Loading state
  if (loading) {
    return <CommandOutputSkeleton />;
  }

  // Error state
  if (error) {
    return (
      <Card className="p-6">
        <div className="text-center text-muted-foreground">
          <Terminal className="w-12 h-12 mx-auto mb-3 opacity-50" />
          <p className="font-medium">Unable to generate install command</p>
          <p className="text-sm mt-1">
            Some packages may not be available for your selected distribution.
            Try selecting different apps or changing your distribution.
          </p>
        </div>
      </Card>
    );
  }

  // No result
  if (!result) {
    return null;
  }

  // Success state with commands
  return (
    <div className="space-y-4">
      <Card className="p-6">
        <div className="space-y-4">
          <CommandHeader
            appCount={selectedApps.size}
            sourcePreference={sourcePreference}
            copied={copiedAll}
            onCopy={handleCopyAll}
            onDownload={handleDownload}
          />

          <SetupCommands
            commands={result.setupCommands || []}
            copied={copiedSetup}
            onCopy={handleCopySetup}
          />

          <InstallCommands
            commands={result.commands}
            breakdown={result.breakdown}
            copiedItems={copiedCommands}
            onCopyCommand={handleCopyCommand}
          />

          <CommandWarnings warnings={result.warnings || []} />
        </div>
      </Card>
    </div>
  );
}
