'use client';

import { useState, useEffect, useRef } from 'react';
import { Copy, Check, Terminal, Download } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { LoadingSpinner } from '@/components/loading-spinner';
import { useCommand } from '@/hooks/use-command';
import { useSelectionStore } from '@/stores/selection-store';
import { toast } from 'sonner';

export function CommandOutput() {
  const { selectedApps, selectedDistro, sourcePreference } = useSelectionStore();
  const { generate, loading, error, result } = useCommand();
  const [copied, setCopied] = useState(false);
  const [copiedSetup, setCopiedSetup] = useState(false);
  const [copiedCommands, setCopiedCommands] = useState<Record<number, boolean>>({});

  // Track previous values to prevent unnecessary calls
  const prevSelectionRef = useRef<{
    appIds: string;
    distro: string | null;
    source: string | null;
  }>({
    appIds: '',
    distro: null,
    source: null,
  });

  // Auto-generate when selection actually changes
  useEffect(() => {
    const appIds = Array.from(selectedApps).sort().join(',');
    const prev = prevSelectionRef.current;

    // Check if selection actually changed
    const hasChanged =
      prev.appIds !== appIds ||
      prev.distro !== selectedDistro ||
      prev.source !== sourcePreference;

    if (hasChanged && selectedApps.size > 0 && selectedDistro) {
      prevSelectionRef.current = {
        appIds,
        distro: selectedDistro,
        source: sourcePreference,
      };
      generate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedApps, selectedDistro, sourcePreference]);

  const handleCopy = async () => {
    if (!result) return;

    const fullCommand = [
      ...(result.setupCommands || []),
      ...result.commands,
    ].join('\n\n');

    try {
      await navigator.clipboard.writeText(fullCommand);
      setCopied(true);
      toast.success('Copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.error('Failed to copy to clipboard');
    }
  };

  const handleCopySetup = async () => {
    if (!result?.setupCommands) return;

    try {
      await navigator.clipboard.writeText(result.setupCommands.join('\n\n'));
      setCopiedSetup(true);
      toast.success('Setup commands copied!');
      setTimeout(() => setCopiedSetup(false), 2000);
    } catch (err) {
      toast.error('Failed to copy to clipboard');
    }
  };

  const handleCopyCommand = async (index: number) => {
    if (!result) return;

    try {
      await navigator.clipboard.writeText(result.commands[index]);
      setCopiedCommands({ ...copiedCommands, [index]: true });
      toast.success('Command copied!');
      setTimeout(() => {
        setCopiedCommands((prev) => {
          const newState = { ...prev };
          delete newState[index];
          return newState;
        });
      }, 2000);
    } catch (err) {
      toast.error('Failed to copy to clipboard');
    }
  };

  const handleDownload = () => {
    if (!result) return;

    const fullCommand = [
      '#!/bin/bash',
      '# Generated by Linite - Bulk Linux package installer',
      '# https://linite.example.com',
      '',
      ...(result.setupCommands || []),
      '',
      ...result.commands,
    ].join('\n');

    const blob = new Blob([fullCommand], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'linite-install.sh';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Script downloaded!');
  };

  if (selectedApps.size === 0 || !selectedDistro) {
    return (
      <Card className="p-6">
        <div className="text-center text-muted-foreground">
          <Terminal className="w-12 h-12 mx-auto mb-3 opacity-50" />
          <p className="font-medium">No command generated yet</p>
          <p className="text-sm mt-1">
            Select a distribution and some apps to get started
          </p>
        </div>
      </Card>
    );
  }

  if (loading) {
    return (
      <Card className="p-6">
        <div className="flex flex-col items-center gap-3">
          <LoadingSpinner />
          <p className="text-sm text-muted-foreground">
            Generating install command...
          </p>
        </div>
      </Card>
    );
  }

  if (error) {
    return (
      <Card className="p-6 border-destructive">
        <div className="text-center text-destructive">
          <p className="font-medium">Failed to generate command</p>
          <p className="text-sm mt-1">{error}</p>
        </div>
      </Card>
    );
  }

  if (!result) {
    return null;
  }

  return (
    <div className="space-y-4">
      <Card className="p-6">
        <div className="space-y-4">
          {/* Header */}
          <div className="flex items-start justify-between">
            <div>
              <h3 className="font-semibold text-lg flex items-center gap-2">
                <Terminal className="w-5 h-5" />
                Install Command
              </h3>
              <p className="text-sm text-muted-foreground mt-1">
                {selectedApps.size} {selectedApps.size === 1 ? 'app' : 'apps'} selected
                {sourcePreference && ` • Preferring ${sourcePreference}`}
              </p>
            </div>

            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={handleDownload}
                className="gap-2"
              >
                <Download className="w-4 h-4" />
                Download
              </Button>
              <Button
                variant="default"
                size="sm"
                onClick={handleCopy}
                className="gap-2"
              >
                {copied ? (
                  <>
                    <Check className="w-4 h-4" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    Copy
                  </>
                )}
              </Button>
            </div>
          </div>

          {/* Setup Commands */}
          {result.setupCommands && result.setupCommands.length > 0 && (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Badge variant="secondary">Setup</Badge>
                  <span className="text-sm text-muted-foreground">
                    Run these first
                  </span>
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleCopySetup}
                  className="h-8 px-2 gap-1.5"
                >
                  {copiedSetup ? (
                    <Check className="w-3.5 h-3.5" />
                  ) : (
                    <Copy className="w-3.5 h-3.5" />
                  )}
                  <span className="text-xs">
                    {copiedSetup ? 'Copied' : 'Copy'}
                  </span>
                </Button>
              </div>
              <div className="bg-muted rounded-md p-4 font-mono text-sm overflow-x-auto">
                {result.setupCommands.map((cmd, i) => (
                  <div key={i} className="whitespace-pre-wrap">
                    {cmd}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Install Commands */}
          <div className="space-y-3">
            {result.breakdown.map((item, i) => (
              <div key={i} className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Badge variant="outline">{item.source}</Badge>
                    <span className="text-xs text-muted-foreground">
                      {item.packages.length}{' '}
                      {item.packages.length === 1 ? 'package' : 'packages'}
                    </span>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleCopyCommand(i)}
                    className="h-8 px-2 gap-1.5"
                  >
                    {copiedCommands[i] ? (
                      <Check className="w-3.5 h-3.5" />
                    ) : (
                      <Copy className="w-3.5 h-3.5" />
                    )}
                    <span className="text-xs">
                      {copiedCommands[i] ? 'Copied' : 'Copy'}
                    </span>
                  </Button>
                </div>
                <div className="bg-muted rounded-md p-4 font-mono text-sm overflow-x-auto">
                  <div className="whitespace-pre-wrap">{result.commands[i]}</div>
                </div>
              </div>
            ))}
          </div>

          {/* Warnings */}
          {result.warnings && result.warnings.length > 0 && (
            <div className="space-y-2">
              <Badge variant="destructive">Warnings</Badge>
              <div className="bg-destructive/10 border border-destructive/20 rounded-md p-4 text-sm space-y-1">
                {result.warnings.map((warning, i) => (
                  <p key={i} className="text-destructive">
                    • {warning}
                  </p>
                ))}
              </div>
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}
